// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface TxTraceLib$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "TxTraceLib";
  readonly sourceName: "contracts/shared/TxTraceLib.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220d59c3b76013ee9a913be0ef58412810a0bf3bb604ff4d031c869d2e7a39a954a64736f6c634300081c0033";
  readonly deployedBytecode: "0x5f80fdfea2646970667358221220d59c3b76013ee9a913be0ef58412810a0bf3bb604ff4d031c869d2e7a39a954a64736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/shared/TxTraceLib.sol";
  readonly buildInfoId: "solc-0_8_28-0d9265d8ada8037043f357ec85ca79820f4a6a6d";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["TxTraceLib"]: TxTraceLib$Type;
    ["contracts/shared/TxTraceLib.sol:TxTraceLib"]: TxTraceLib$Type;
  }
}