// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IERC7579Hook$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IERC7579Hook";
  readonly sourceName: "contracts/erc7579/IERC7579Hook.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes","name":"hookData","type":"bytes"}],"name":"postCheck","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"msgSender","type":"address"},{"internalType":"uint256","name":"value","type":"uint256"},{"internalType":"bytes","name":"msgData","type":"bytes"}],"name":"preCheck","outputs":[{"internalType":"bytes","name":"hookData","type":"bytes"}],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/erc7579/IERC7579Hook.sol";
  readonly buildInfoId: "solc-0_8_28-99d79b6a4b6fb23a544895c493aaf3feb9569fa1";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IERC7579Hook"]: IERC7579Hook$Type;
    ["contracts/erc7579/IERC7579Hook.sol:IERC7579Hook"]: IERC7579Hook$Type;
  }
}