// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IERC6900ExecutionHookModule$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IERC6900ExecutionHookModule";
  readonly sourceName: "contracts/erc6900/IERC6900Hooks.sol";
  readonly abi: [{"inputs":[{"internalType":"uint32","name":"entityId","type":"uint32"},{"internalType":"bytes","name":"preExecHookData","type":"bytes"}],"name":"postExecutionHook","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint32","name":"entityId","type":"uint32"},{"internalType":"address","name":"sender","type":"address"},{"internalType":"uint256","name":"value","type":"uint256"},{"internalType":"bytes","name":"data","type":"bytes"}],"name":"preExecutionHook","outputs":[{"internalType":"bytes","name":"hookData","type":"bytes"}],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/erc6900/IERC6900Hooks.sol";
  readonly buildInfoId: "solc-0_8_28-99d79b6a4b6fb23a544895c493aaf3feb9569fa1";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IERC6900ExecutionHookModule"]: IERC6900ExecutionHookModule$Type;
    ["contracts/erc6900/IERC6900Hooks.sol:IERC6900ExecutionHookModule"]: IERC6900ExecutionHookModule$Type;
  }
}