// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface EIP7906ExtendedLibrary$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "EIP7906ExtendedLibrary";
  readonly sourceName: "contracts/shared/EIP7906ExtendedLibrary.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"actual","type":"uint256"},{"internalType":"uint256","name":"minimum","type":"uint256"}],"name":"InsufficientOutput","type":"error"},{"inputs":[{"internalType":"address","name":"target","type":"address"},{"internalType":"bytes32","name":"slot","type":"bytes32"}],"name":"ProtectedSlotModified","type":"error"},{"inputs":[{"internalType":"address","name":"addr","type":"address"}],"name":"UnexpectedRecipient","type":"error"},{"inputs":[{"internalType":"uint256","name":"actual","type":"uint256"},{"internalType":"uint256","name":"max","type":"uint256"}],"name":"UnlimitedApprovalDetected","type":"error"}];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea26469706673582212201c95e6ab2b6bbb7bab8c36ab4a025acf62c166297f1ed66796cc8611f162828664736f6c634300081c0033";
  readonly deployedBytecode: "0x5f80fdfea26469706673582212201c95e6ab2b6bbb7bab8c36ab4a025acf62c166297f1ed66796cc8611f162828664736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/shared/EIP7906ExtendedLibrary.sol";
  readonly buildInfoId: "solc-0_8_28-0d9265d8ada8037043f357ec85ca79820f4a6a6d";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["EIP7906ExtendedLibrary"]: EIP7906ExtendedLibrary$Type;
    ["contracts/shared/EIP7906ExtendedLibrary.sol:EIP7906ExtendedLibrary"]: EIP7906ExtendedLibrary$Type;
  }
}