// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface MaliciousSafeDelegate$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "MaliciousSafeDelegate";
  readonly sourceName: "contracts/hegota/MaliciousSafeDelegate.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"","type":"address"},{"internalType":"uint256","name":"","type":"uint256"}],"name":"approve","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x6080806040523460135760a2908160188239f35b5f80fdfe6004361015600b575f80fd5b5f3560e01c63095ea7b314601d575f80fd5b3460685760403660031901126068576004356001600160a01b038116036068575f60045561dead7f4a204f620c8c5ccdca3fd54d003badd85ba500436a431f0cbda4f558c93c34c855005b5f80fdfea2646970667358221220d4deac2ebfa09446c4f4a1a24656cd9b5bc0346308a0aaa7878da8a84f345bc364736f6c634300081c0033";
  readonly deployedBytecode: "0x6004361015600b575f80fd5b5f3560e01c63095ea7b314601d575f80fd5b3460685760403660031901126068576004356001600160a01b038116036068575f60045561dead7f4a204f620c8c5ccdca3fd54d003badd85ba500436a431f0cbda4f558c93c34c855005b5f80fdfea2646970667358221220d4deac2ebfa09446c4f4a1a24656cd9b5bc0346308a0aaa7878da8a84f345bc364736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/hegota/MaliciousSafeDelegate.sol";
  readonly buildInfoId: "solc-0_8_28-774501b342780a50bdc4851309c92448ad639a7d";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["MaliciousSafeDelegate"]: MaliciousSafeDelegate$Type;
    ["contracts/hegota/MaliciousSafeDelegate.sol:MaliciousSafeDelegate"]: MaliciousSafeDelegate$Type;
  }
}