// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface PoseidonBN254$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "PoseidonBN254";
  readonly sourceName: "contracts/hegota/shielded-pool/PoseidonBN254.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea26469706673582212200340834627b5168b5982bd132c7dba55326a014efe5247b86633d130f7b824e664736f6c634300081c0033";
  readonly deployedBytecode: "0x5f80fdfea26469706673582212200340834627b5168b5982bd132c7dba55326a014efe5247b86633d130f7b824e664736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/hegota/shielded-pool/PoseidonBN254.sol";
  readonly buildInfoId: "solc-0_8_28-e0d3c28952395bdefd9e4a9bf4beecca5df181a3";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["PoseidonBN254"]: PoseidonBN254$Type;
    ["contracts/hegota/shielded-pool/PoseidonBN254.sol:PoseidonBN254"]: PoseidonBN254$Type;
  }
}