// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface DemoExecutor$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "DemoExecutor";
  readonly sourceName: "contracts/shared/DemoExecutor.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"safe","type":"address"},{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"value","type":"uint256"},{"internalType":"bytes","name":"data","type":"bytes"}],"name":"execute","outputs":[],"stateMutability":"payable","type":"function"}];
  readonly bytecode: "0x60808060405234601557610225908161001a8239f35b5f80fdfe6080806040526004361015610012575f80fd5b5f3560e01c639aefaff814610025575f80fd5b60803660031901126101a2576004356001600160a01b03811691908290036101a2576024356001600160a01b038116908190036101a2576044359260643567ffffffffffffffff81116101a257366023820112156101a25780600401359467ffffffffffffffff86116101a25736602487840101116101a257602060249461016487838099013081525f6040830152600160f81b6060830152604182526100cd6061836101b9565b8a6040519b8c9a8b998a9763353b090160e11b89526004890152898289015261014060448901528261014489015201858701375f848287010152601f80199101168401915f60648601525f60848601525f60a48601525f60c48601525f60e48601525f610104860152600319848685030101610124860152518091818585015261018484015e5f8282018401860152601f01601f191601010301925af180156101ae5761017657005b6020813d6020116101a6575b8161018f602093836101b9565b810103126101a25751801515036101a257005b5f80fd5b3d9150610182565b6040513d5f823e3d90fd5b90601f8019910116810190811067ffffffffffffffff8211176101db57604052565b634e487b7160e01b5f52604160045260245ffdfea26469706673582212203ecd3bfe1d228347111bdc18b02b4f0809635bee47d0e60ca211ae077e2eb9df64736f6c634300081c0033";
  readonly deployedBytecode: "0x6080806040526004361015610012575f80fd5b5f3560e01c639aefaff814610025575f80fd5b60803660031901126101a2576004356001600160a01b03811691908290036101a2576024356001600160a01b038116908190036101a2576044359260643567ffffffffffffffff81116101a257366023820112156101a25780600401359467ffffffffffffffff86116101a25736602487840101116101a257602060249461016487838099013081525f6040830152600160f81b6060830152604182526100cd6061836101b9565b8a6040519b8c9a8b998a9763353b090160e11b89526004890152898289015261014060448901528261014489015201858701375f848287010152601f80199101168401915f60648601525f60848601525f60a48601525f60c48601525f60e48601525f610104860152600319848685030101610124860152518091818585015261018484015e5f8282018401860152601f01601f191601010301925af180156101ae5761017657005b6020813d6020116101a6575b8161018f602093836101b9565b810103126101a25751801515036101a257005b5f80fd5b3d9150610182565b6040513d5f823e3d90fd5b90601f8019910116810190811067ffffffffffffffff8211176101db57604052565b634e487b7160e01b5f52604160045260245ffdfea26469706673582212203ecd3bfe1d228347111bdc18b02b4f0809635bee47d0e60ca211ae077e2eb9df64736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/shared/DemoExecutor.sol";
  readonly buildInfoId: "solc-0_8_28-99d79b6a4b6fb23a544895c493aaf3feb9569fa1";
};

export interface ISafe$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ISafe";
  readonly sourceName: "contracts/shared/DemoExecutor.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"value","type":"uint256"},{"internalType":"bytes","name":"data","type":"bytes"},{"internalType":"enum Enum.Operation","name":"operation","type":"uint8"},{"internalType":"uint256","name":"safeTxGas","type":"uint256"},{"internalType":"uint256","name":"baseGas","type":"uint256"},{"internalType":"uint256","name":"gasPrice","type":"uint256"},{"internalType":"address","name":"gasToken","type":"address"},{"internalType":"address payable","name":"refundReceiver","type":"address"},{"internalType":"bytes","name":"signatures","type":"bytes"}],"name":"execTransaction","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"payable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/shared/DemoExecutor.sol";
  readonly buildInfoId: "solc-0_8_28-99d79b6a4b6fb23a544895c493aaf3feb9569fa1";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["DemoExecutor"]: DemoExecutor$Type
    ["ISafe"]: ISafe$Type;
    ["contracts/shared/DemoExecutor.sol:DemoExecutor"]: DemoExecutor$Type
    ["contracts/shared/DemoExecutor.sol:ISafe"]: ISafe$Type;
  }
}