// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface BenignSafeDelegate$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "BenignSafeDelegate";
  readonly sourceName: "contracts/hegota/BenignSafeDelegate.sol";
  readonly abi: [{"inputs":[],"name":"noop","outputs":[],"stateMutability":"pure","type":"function"}];
  readonly bytecode: "0x608080604052346013576067908160188239f35b5f80fdfe6004361015600b575f80fd5b5f3560e01c635dfc2e4a14601d575f80fd5b34602d575f366003190112602d57005b5f80fdfea26469706673582212203432bd414a7a31a71d847360a87364617e9ad742ecf0e584031bc79ba4c46b6264736f6c634300081c0033";
  readonly deployedBytecode: "0x6004361015600b575f80fd5b5f3560e01c635dfc2e4a14601d575f80fd5b34602d575f366003190112602d57005b5f80fdfea26469706673582212203432bd414a7a31a71d847360a87364617e9ad742ecf0e584031bc79ba4c46b6264736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/hegota/BenignSafeDelegate.sol";
  readonly buildInfoId: "solc-0_8_28-e763f92f75b9772e9eaa3fe5b0d0c73867031c78";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["BenignSafeDelegate"]: BenignSafeDelegate$Type;
    ["contracts/hegota/BenignSafeDelegate.sol:BenignSafeDelegate"]: BenignSafeDelegate$Type;
  }
}