// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IMinimalExecutor$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IMinimalExecutor";
  readonly sourceName: "contracts/erc7579/IMinimalValidatorExecutor.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"smartAccount","type":"address"}],"name":"isInitialized","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"moduleTypeId","type":"uint256"}],"name":"isModuleType","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"bytes","name":"data","type":"bytes"}],"name":"onInstall","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"bytes","name":"data","type":"bytes"}],"name":"onUninstall","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/erc7579/IMinimalValidatorExecutor.sol";
  readonly buildInfoId: "solc-0_8_28-99d79b6a4b6fb23a544895c493aaf3feb9569fa1";
};

export interface IMinimalModule$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IMinimalModule";
  readonly sourceName: "contracts/erc7579/IMinimalValidatorExecutor.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"smartAccount","type":"address"}],"name":"isInitialized","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"moduleTypeId","type":"uint256"}],"name":"isModuleType","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"bytes","name":"data","type":"bytes"}],"name":"onInstall","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"bytes","name":"data","type":"bytes"}],"name":"onUninstall","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/erc7579/IMinimalValidatorExecutor.sol";
  readonly buildInfoId: "solc-0_8_28-99d79b6a4b6fb23a544895c493aaf3feb9569fa1";
};

export interface IMinimalValidator$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IMinimalValidator";
  readonly sourceName: "contracts/erc7579/IMinimalValidatorExecutor.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"smartAccount","type":"address"}],"name":"isInitialized","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"moduleTypeId","type":"uint256"}],"name":"isModuleType","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"sender","type":"address"},{"internalType":"bytes32","name":"hash","type":"bytes32"},{"internalType":"bytes","name":"signature","type":"bytes"}],"name":"isValidSignatureWithSender","outputs":[{"internalType":"bytes4","name":"","type":"bytes4"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"bytes","name":"data","type":"bytes"}],"name":"onInstall","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"bytes","name":"data","type":"bytes"}],"name":"onUninstall","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/erc7579/IMinimalValidatorExecutor.sol";
  readonly buildInfoId: "solc-0_8_28-99d79b6a4b6fb23a544895c493aaf3feb9569fa1";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IMinimalExecutor"]: IMinimalExecutor$Type
    ["IMinimalModule"]: IMinimalModule$Type
    ["IMinimalValidator"]: IMinimalValidator$Type;
    ["contracts/erc7579/IMinimalValidatorExecutor.sol:IMinimalExecutor"]: IMinimalExecutor$Type
    ["contracts/erc7579/IMinimalValidatorExecutor.sol:IMinimalModule"]: IMinimalModule$Type
    ["contracts/erc7579/IMinimalValidatorExecutor.sol:IMinimalValidator"]: IMinimalValidator$Type;
  }
}