// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface MockProxy$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "MockProxy";
  readonly sourceName: "contracts/shared/MockProxy.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"_implementation","type":"address"}],"stateMutability":"nonpayable","type":"constructor"},{"inputs":[],"name":"implementation","outputs":[{"internalType":"address","name":"impl","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"_impl","type":"address"}],"name":"setImplementation","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x608034607b57601f61018238819003918201601f19168301916001600160401b03831184841017607f57808492602094604052833981010312607b57516001600160a01b0381168103607b577f360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc5560405160ee90816100948239f35b5f80fd5b634e487b7160e01b5f52604160045260245ffdfe60808060405260043610156011575f80fd5b5f3560e01c9081635c60da1b146078575063d784d42614602f575f80fd5b3460745760203660031901126074576004356001600160a01b03811681036074577f360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc55005b5f80fd5b346074575f3660031901126074577f360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc546001600160a01b03168152602090f3fea26469706673582212208c3767f131fa4ae036b9ca173f7fcb34ac1ee323c2c86e630f25c085994eca5c64736f6c634300081c0033";
  readonly deployedBytecode: "0x60808060405260043610156011575f80fd5b5f3560e01c9081635c60da1b146078575063d784d42614602f575f80fd5b3460745760203660031901126074576004356001600160a01b03811681036074577f360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc55005b5f80fd5b346074575f3660031901126074577f360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc546001600160a01b03168152602090f3fea26469706673582212208c3767f131fa4ae036b9ca173f7fcb34ac1ee323c2c86e630f25c085994eca5c64736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/shared/MockProxy.sol";
  readonly buildInfoId: "solc-0_8_28-99d79b6a4b6fb23a544895c493aaf3feb9569fa1";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["MockProxy"]: MockProxy$Type;
    ["contracts/shared/MockProxy.sol:MockProxy"]: MockProxy$Type;
  }
}